chain_genesis_hash: 1b9f147d7b41205eda0b98645a63b75744902bb640e0543975fe8a64ec29f1e9
rpc_address: 192.168.58.110:13120
archive_center_http_url: http://192.168.58.110:13119
request_second_limit: 10 
tls_enable: false 
tls: 
  server_name: baec-archive
  priv_key_file: ./archivecenter/archive-client.key
  cert_file: ./archivecenter/archive-client.pem
  trust_ca_list:
    - ./archivecenter/baec-root.pem
max_send_msg_size: 200
max_recv_msg_size: 200 