chain_genesis_hash: a840c4e495975d90b4c5bb7d0b7641df8028163667132d0d0ab06b876987b433
rpc_address: 172.25.138.51:13120
archive_center_http_url: http://172.25.138.51:13119
request_second_limit: 10 
tls_enable: false 
tls: 
  server_name: baec-archive
  priv_key_file: ./archivecenter/archive-client.key
  cert_file: ./archivecenter/archive-client.pem
  trust_ca_list:
    - ./archivecenter/baec-root.pem
max_send_msg_size: 200
max_recv_msg_size: 200 