log:
  # Logger configuration file path.
  log_path: ./bfdb_clean_log 
  log_level: debug   
  log_size: 100
  log_age: 30
  log_num: 100
bfdb_path: ./
mode: 1 # 1 为输出清理信息模式; 2 为根据输出的清理信息,做文件清理；默认为1 
clean_stub: ./stub20221021151245.csv # 为清理信息模式输出的文件 
clean_height: 250  # 可以清理的区块的最大高度 
archive_center_config:
  chain_genesis_hash: 5b29b0a67c529352c0e3f512a4e8d329f967afcdb580ec76e6d1462d9ac969ec
  archive_center_http_url: http://127.0.0.1:13119
  request_second_limit: 10
